### PR TITLE
Correctly handle multiple user errors

### LINKED ISSUE #59: `ShopifyAPI::Errors::HttpResponseError` fields property just contains the first failing field if passing an array
I've created a mutation to set metafields:

```ruby
class SetMetafields
  include ShopifyGraphql::Mutation

  MUTATION = <<~GRAPHQL
    mutation MetafieldsSet($input: [MetafieldsSetInput!]!) {
      metafieldsSet(metafields: $input) {
        metafields {
          id
        }
        userErrors {
          field
          message
          code
        }
      }
    }
  GRAPHQL

  def call(input:)
    response = execute(MUTATION, input: normalize_input(input))
    handle_user_errors response.data.metafieldsSet
    response.data = response.data.metafieldsSet.metafields
    response
  end

  private

  # ...
end
```

If I pass two (or more) metafields that will fail because of definition validation, I get just get the first one on the `.fields` property:

```ruby
def test_failing_set_metafields
  SetMetafields.call(input: [ {
  namespace: "custom",
  key: "text_5_10_chars",
  value: "fail",
  type: "single_line_text_field",
  owner_id: "gid://shopify/Customer/23151671050566"
}, {
  namespace: "custom",
  key: "birthday",
  value: "2025-01-01",
  type: "date",
  owner_id: "gid://shopify/Customer/23151671050566"
} ])
rescue ShopifyAPI::Errors::HttpResponseError => e
  puts "Fields: #{e.fields}"
  puts "Response: #{e.response.body}"
end

# Output

Fields: ["metafields", "0", "value"]
Response: #<OpenStruct metafields=[], userErrors=[#<OpenStruct field=["metafields", "0", "value"], message="Value has a minimum length of 5.", code="INVALID_VALUE">, #<OpenStruct field=["metafields", "1", "value"], message="Value has a maximum of 2024-10-09.", code="INVALID_VALUE">]>
```

Shouldn't the fields array looks like: `["metafields", ["0", "1"], "value"]` ?

Gems versions:
- shopify_app: 22.5.1
- shopify_api: 14.7.0
- shopify_graphql: 2.0.1 (latest)

### PR DESCRIPTION
**Pull request by BaggioGiacomo**
- closes #59 

This PR fixes how multiple user errors are managed.

`error.message` will return:

```
2 fields have failed:

- Response code = INVALID_VALUE. Response message = Value has a minimum length of 5. Field = ["metafields", "0", "value"].

- Response code = INVALID_VALUE. Response message = Value has a minimum length of 5. Field = ["metafields", "3", "value"].
```

`error.messages` will return:

```
["Value has a minimum length of 5.", "Value has a minimum of 11111."]
```

`error.fields` will return:

```
[["metafields", "0", "value"], ["metafields", "3", "value"]]
```

`error.error_codes` will return:

```
["INVALID_VALUE", "INVALID_VALUE"]
```

### CODE REVIEW

File: lib/shopify_graphql/exceptions.rb [hunk 1]
```diff
@@ -1,6 +1,6 @@
 module ShopifyGraphql
   class ConnectionError < ShopifyAPI::Errors::HttpResponseError
-    attr_accessor :error_code, :fields
+    attr_accessor :error_codes, :fields, :messages
```
Comment (BaggioGiacomo) [inline lib/shopify_graphql/exceptions.rb:3]: `error_code` has become `error_codes` so we can handle both single and multiple errors

I've added the `messages` attribute so the user can easily get the error messages

File: lib/shopify_graphql/client.rb [hunk 2]
```diff
@@ -113,35 +113,59 @@ def handle_graphql_errors(response)
         else
           ConnectionError.new(response: response)
         end
-      exception.error_code = error_code
```
Comment (kirillplatonov) [inline lib/shopify_graphql/client.rb:116]: It would be great to keep existing `exception.error_code` as an alias for first error. This will prevent breaking change in the gem and in many cases we only care about single error in the app, so we could continue using `error_code`.

File: lib/shopify_graphql/client.rb [hunk 3]
```diff
@@ -113,35 +113,59 @@ def handle_graphql_errors(response)
...
-        fields: error.field,
+      errors = response.userErrors
+      error_message = generate_user_errors_message(
+        messages: errors.map(&:message),
+        codes: errors.map(&:code),
+        fields: errors.map(&:field),
       )
 
       exception = UserError.new(response: response)
-      exception.error_code = error_code
```
Comment (kirillplatonov) [inline lib/shopify_graphql/client.rb:132]: And here too

File: lib/shopify_graphql/exceptions.rb (hunk 1 above)
Comment (kirillplatonov) [reply lib/shopify_graphql/exceptions.rb:3]: Let's keep `error_code` here too.

File: test/error_handling_test.rb [hunk 4]
```diff
@@ -43,9 +43,10 @@ class ErrorHandlingTest < ActiveSupport::TestCase
       ShopifyGraphql::Client.new.handle_user_errors(response.data.metafieldDefinitionCreate)
     rescue ShopifyGraphql::UserError => error
       assert_equal 200, error.code
-      assert_equal "TAKEN", error.error_code
```
Comment (kirillplatonov) [inline test/error_handling_test.rb:46]: And keep tests for `error_code`

**Review by kirillplatonov — CHANGES_REQUESTED** [review]
Sorry for delay with review. It looks great! The only suggestion is to keep `error_code` as an alias for first error code for compatibility.

**Comment by kirillplatonov** [comment]
@BaggioGiacomo Thank you for quick changes! I'll test changes on production for a 1-2 week and release new version.

**Comment by kirillplatonov** [comment]
Published in [v2.2.0](https://github.com/kirillplatonov/shopify_graphql/releases/tag/v2.2.0)
